Updates for 100.10 (#68)
Esri/indoor-routing-xamarin pull request #69
Opened 2021-01-23 07:24 UTC by nCastle1

* Removes support for iOS 12
* Update RELEASE.md
* Bump to 100.10

2021-02-19 06:49 UTC, nCastle1 commented
Fully tested, everything working as expected.

2021-02-19 18:04 UTC, esreli requested changes
Because it would be difficult for me to check myself, I'm trusting your work here that the app version has been updated in all locations. I have a few small suggestions but otherwise this looks ready to go 👍

2021-02-19 18:04 UTC, esreli commented on docs/README.md
> +Once search is complete and a feature is selected on the map, the route icon appears on the bottom card. Tapping that navigates the app to the routing page, where user is prompted to add a Start and
I scratched my head reading `[...]/routing/routing/` at first but after checking for my self it looks good to me!

2021-02-22 19:37 UTC, esreli approved these changes
👍

2021-02-22 20:03 UTC, merged